<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>__Namespace__.AppHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <!--#if (IncludeOrleans) -->
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <!--#endif -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\__ProjectName__\__ProjectName__.csproj" />
  </ItemGroup>

</Project>
