// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rOVQPOOOVQPO'#CoOVQPO'#CpQqQQOOOOQO'#Cx'#CxO!oQQO,59ZO#SQQO,59[OOQO'#Cc'#CcOOQO'#Cd'#CdOOQO'#Ce'#CeOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Ch'#ChOOQO'#Ci'#CiOOQO'#Cj'#CjOOQO'#Ck'#CkOOQO'#Cl'#ClOOQO'#Cm'#CmOOQO'#Cn'#CnOVQPO,59]O#ZQPO'#CsOOQO,59^,59^OVQPO,58|OVQPO,58|OVQPO,58|OVQPO,58|OVQPO,58|OOQO1G.v1G.vO#bQQO1G.wO#iQQO'#D]O#sQPO,59_O%SQQO1G.hO%ZQQO1G.hO&iQQO1G.hO&sQQO1G.hO&}QQO1G.hOVQPO7+$cOVQPO'#CtO'UQPO,59wOOQO1G.y1G.yOOQO7+$S7+$SO(XQQO<<G}O(oQQO,59`OOQO-E6r-E6r",
  stateData: "(y~OkOS~OQSORSOSSOTSOpPOqPOzPO{QO~OmVOnWOoXOpYOqZOr[Os]Ot^Ou_Ov`OwaOxbO{dO}cO~Oica|ca!Oca!Qcayca~PqO|kO~PqO|!PP~PVO!OtO~PqO!QuO|!PX~PqO|wO~O{dOiUinUioUipUiqUirUisUitUiuUivUiwUixUi}Ui|Ui!OUi!QUiyUi~OmUi~P#xOmVO~P#xOmVOnWOoXO{dOiUirUisUitUiuUivUiwUixUi}Ui|Ui!OUi!QUiyUi~OpUiqUi~P%bOpYOqZO~P%bOyxO~PqO!QuO|!Pa~OmVOnWOoXOpYOqZOr[Os]Ot^Ou_Ov`OwaO{dO}cO~Oieyxey|ey!Oey!Qeyyey~P'^O|ha!Qha~PqO",
  goto: "$w!QPPPPPP!R!a!n!n!z!z#V#V#V#V#V#V#a!R!R!R!R#j#xPPP$OPPPPPPPPPPPPPPPPPP$tiSOPQcdfghijtugfRTUlmpqrsyzegRTUlmqrsyzchRTUlmrsyzaiRTUlmsyz_jRTUlmszieRTUlmopqrsyzQvmR{vQROQTPQUQQlcQmdQofQpgQqhQriQsjQytRzuRnd",
  nodeNames: "⚠ EvalProgram Reference Identifier Number String BinaryExpression Call Call Call Call Call Call Call Call Call Call Call Call UnaryExpression ParenthesizedExpression ConditionalExpression CallExpression ArgList",
  maxTerm: 48,
  nodeProps: [
    ["group", -9,2,3,4,5,6,19,20,21,22,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "'w~RpX^#Vpq#Vqr#zrs$Xtu$vxy%byz%gz{%l{|%q|}%v}!O%{!O!P&Q!P!Q&V!Q![&[![!]&d!^!_&i!_!`&v!`!a&{!a!b'Y!c!}'_!}#O'm#P#Q'r#R#S'_#T#o'_#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Yk~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#VR$PPzP!_!`$SQ$XOuQ~$[TOr$Xrs$ks;'S$X;'S;=`$p<%lO$X~$pOT~~$sP;=`<%l$X~$yR!c!}%S#R#S%S#T#o%S~%XRQ~!c!}%S#R#S%S#T#o%S~%gO{~~%lO|~~%qOo~~%vOp~~%{O!Q~~&QOq~~&VOm~~&[On~~&aPS~!Q![&[~&iO!O~~&nPr~!_!`&q~&vOv~~&{Ot~~'QPs~!_!`'T~'YOw~~'_O}~~'dRR~!c!}'_#R#S'_#T#o'_~'rOx~~'wOy~",
  tokenizers: [0, 1],
  topRules: {"EvalProgram":[0,1]},
  tokenPrec: 0
})
