// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EvalProgram = 1,
  Reference = 2,
  Identifier = 3,
  Number = 4,
  String = 5,
  BinaryExpression = 6,
  UnaryExpression = 19,
  ParenthesizedExpression = 20,
  ArgList = 23
