// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EvalProgram = 1,
  Identifier = 2,
  Number = 3,
  String = 4,
  BinaryExpression = 5,
  UnaryExpression = 18
