// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EvalProgram = 1,
  Reference = 2,
  Identifier = 3,
  BooleanLiteral = 4,
  Number = 5,
  String = 6,
  BinaryExpression = 7,
  UnaryExpression = 20,
  ParenthesizedExpression = 21,
  ArgList = 24
