// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WOVQPOOOVQPO'#CnQkQQOOOOQO'#Cs'#CsO!fQQO,59YOOQO'#Cb'#CbOOQO'#Cc'#CcOOQO'#Cd'#CdOOQO'#Ce'#CeOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Ch'#ChOOQO'#Ci'#CiOOQO'#Cj'#CjOOQO'#Ck'#CkOOQO'#Cl'#ClOOQO'#Cm'#CmOVQPO,59ZOVQPO,58{OVQPO,58{OVQPO,58{OVQPO,58{OVQPO,58{O!sQQO1G.uOOQO1G.g1G.gO#xQQO1G.gO$SQQO1G.gO$oQQO1G.gO%fQQO1G.gOVQPO7+$aOOQO7+$R7+$RO%mQQO<<G{",
  stateData: "&d~OfOS~OQRORROSROkPOlPOuPO~OhTOiUOjVOkWOlXOmYOnZOo[Op]Oq^Or_Os`OvaO~Odbawbatba~PkOwmO~PkOhTOdTikTilTimTinTioTipTiqTirTisTivTiwTitTi~OiTijTi~P!zOiUOjVO~P!zOhTOiUOjVOkWOlXO~OdTimTinTioTipTiqTirTisTivTiwTitTi~P$^OtnO~PkOmYOnZOo[Op]Oq^Or_OvaOdcyscywcytcy~P$^O",
  goto: "#ZhPPPPPit!O!O!X!X!a!a!a!a!a!a!hiiPPP!ncROPabcdefmabQSgijklo_cQSgjklo]dQSgkloZeQSgloXfQSglQQOQSPQgaQhbQicQjdQkeQlfRom",
  nodeNames: "⚠ EvalProgram Identifier Number String BinaryExpression Call Call Call Call Call Call Call Call Call Call Call Call UnaryExpression ConditionalExpression",
  maxTerm: 39,
  nodeProps: [
    ["group", -6,2,3,4,5,18,19,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "&p~RlX^!ypq!yqr#nrs#{z{$j{|$o}!O$t!O!P$y!P!Q%O!Q![%T![!]%]!^!_%b!_!`%o!`!a%t!a!b&R!c!}&W!}#O&f#P#Q&k#R#S&W#T#o&W#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#OYf~X^!ypq!y#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!yR#sPuP!_!`#vQ#{OpQ~$OTOr#{rs$_s;'S#{;'S;=`$d<%lO#{~$dOS~~$gP;=`<%l#{~$oOj~~$tOk~~$yOl~~%OOh~~%TOi~~%YPR~!Q![%T~%bOw~~%gPm~!_!`%j~%oOq~~%tOo~~%yPn~!_!`%|~&ROr~~&WOv~~&]RQ~!c!}&W#R#S&W#T#o&W~&kOs~~&pOt~",
  tokenizers: [0, 1],
  topRules: {"EvalProgram":[0,1]},
  tokenPrec: 0
})
